services:
  validator:
    image: docker.io/lifeofpavs/solana-test-validator:latest
    command: [
        "solana-test-validator",
        "-r", # reset
        # Warp to epoch 1
        "-w",
        "648000",
        # Accounts fixtures
        "--account-dir",
        "/test-fixtures",
        # Programs fixtures
        "--bpf-program",
        "SP12tWFxD9oJsVWNavTTBZvMbA6gkAmxtVgxdqvyvhY",
        "/test-fixtures/programs/stake-pool.so",
        "--bpf-program",
        "SPMBzsVUuoHA4Jm6KunbsotaahvVikZs1JyTW6iJvbn",
        "/test-fixtures/programs/stake-pool.so",
        "--bpf-program",
        "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy",
        "/test-fixtures/programs/stake-pool.so",
        # Features
        "--deactivate-feature",
        "9onWzzvCzNC2jfhxxeqRgs5q7nFAAKpCUvkj6T6GJK9i", # deactivate 1 SOL minimum delegation stake
      ]
    volumes:
      - ./test-fixtures:/test-fixtures
    ports:
      - "8899:8899" # http rpc
      - "8900:8900" # websocket rpc
